import { useEffect, useState } from "react";
import { Plus, FileText, Loader2, Trash2, AlertTriangle, Download, Upload, CheckCircle2 } from "lucide-react";
import { documentsApi, vehiclesApi, driversApi } from "../api/endpoints";
import { useToast } from "../context/ToastContext";
import PageHeader from "../components/PageHeader";
import Modal from "../components/Modal";
import ConfirmDialog from "../components/ConfirmDialog";
import EmptyState from "../components/EmptyState";

const EMPTY_FORM = { target: "vehicle", vehicle_id: "", driver_id: "", doc_type: "insurance", doc_number: "", issue_date: "", expiry_date: "", notes: "", file: null };
function daysUntil(dateStr) { if (!dateStr) return null; return Math.ceil((new Date(dateStr) - new Date()) / (1000 * 60 * 60 * 24)); }

export default function Documents() {
  const { push } = useToast(); const [docs, setDocs] = useState([]); const [vehicles, setVehicles] = useState([]); const [drivers, setDrivers] = useState([]); const [loading, setLoading] = useState(true); const [modalOpen, setModalOpen] = useState(false); const [form, setForm] = useState(EMPTY_FORM); const [saving, setSaving] = useState(false); const [deleteTarget, setDeleteTarget] = useState(null); const [uploadingId, setUploadingId] = useState(null);
  const load = () => { setLoading(true); Promise.all([documentsApi.list(), vehiclesApi.list(), driversApi.list()]).then(([d, v, dr]) => { setDocs(d.data); setVehicles(v.data); setDrivers(dr.data); }).finally(() => setLoading(false)); };
  useEffect(load, []);
  const vehicleName = (id) => vehicles.find((v) => v.id === id)?.name;
  const driverName = (id) => drivers.find((d) => d.id === id)?.full_name;
  const openCreate = () => { setForm({ ...EMPTY_FORM }); setModalOpen(true); };
  const handleSubmit = async (e) => { e.preventDefault(); setSaving(true); try { const res = await documentsApi.create({ vehicle_id: form.target === "vehicle" ? Number(form.vehicle_id) : null, driver_id: form.target === "driver" ? Number(form.driver_id) : null, doc_type: form.doc_type, doc_number: form.doc_number || "NOT_UPLOADED", issue_date: form.issue_date || null, expiry_date: form.expiry_date || null, notes: form.notes || null }); if (form.file) await documentsApi.uploadFile(res.data.id, form.file); push(form.file ? "Document and file uploaded" : "Document record added"); setModalOpen(false); load(); } catch (err) { push(err?.response?.data?.detail || "Could not save document", "error"); } finally { setSaving(false); } };
  const uploadFor = async (doc, file) => { if (!file) return; setUploadingId(doc.id); try { await documentsApi.uploadFile(doc.id, file); push("File uploaded successfully"); load(); } catch (err) { push(err?.response?.data?.detail || "Could not upload file", "error"); } finally { setUploadingId(null); } };
  const download = async (doc) => { try { const res = await documentsApi.downloadFile(doc.id); const url = URL.createObjectURL(res.data); const a = document.createElement("a"); a.href = url; a.download = doc.attachment?.original_filename || `${doc.doc_type}.pdf`; document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(url); } catch (err) { push(err?.response?.data?.detail || "Could not download file", "error"); } };
  const handleDelete = async () => { try { await documentsApi.remove(deleteTarget.id); push("Document removed"); load(); } catch (err) { push(err?.response?.data?.detail || "Could not delete document", "error"); } };

  return <div><PageHeader title="Documents" subtitle="Central document storage for vehicle registrations, insurance, PUCs, driver licences and identity records." action={<button className="btn-amber" onClick={openCreate}><Plus size={16} /> Add Document</button>} />
    {loading ? <div className="flex items-center justify-center py-16 text-navy-400"><Loader2 className="animate-spin mr-2" size={18} /> Loading documents...</div> : docs.length === 0 ? <div className="card"><EmptyState icon={FileText} title="No documents on file" message="Add a document or create a vehicle/driver with its document records." /></div> : <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">{docs.map((d) => { const days = daysUntil(d.expiry_date); const expiringSoon = days !== null && days <= 30 && days >= 0; const expired = days !== null && days < 0; const owner = d.vehicle_id ? `Vehicle: ${vehicleName(d.vehicle_id) || "—"}` : d.driver_id ? `Driver: ${driverName(d.driver_id) || "—"}` : "—"; return <div key={d.id} className={`card p-5 ${expired ? "border-rose-200" : expiringSoon ? "border-amber/60" : ""}`}>
      <div className="flex items-start justify-between mb-2"><div className="flex items-center gap-2.5"><div className="h-9 w-9 rounded-lg bg-navy-800 text-white flex items-center justify-center"><FileText size={16} /></div><div><p className="font-semibold text-navy-800 capitalize">{d.notes || d.doc_type.replace(/_/g, " ")}</p><p className="text-xs text-navy-400 font-mono">{d.doc_number === "NOT_UPLOADED" ? "No document number" : d.doc_number}</p></div></div><button onClick={() => setDeleteTarget(d)} className="rounded-lg p-1.5 text-navy-300 hover:bg-rose-50 hover:text-rose-600"><Trash2 size={15} /></button></div>
      <p className="text-xs text-navy-500 mb-2">{owner}</p>
      {d.expiry_date && <p className={`text-xs font-medium mb-3 flex items-center gap-1 ${expired ? "text-rose-600" : expiringSoon ? "text-amber-dark" : "text-navy-500"}`}>{(expired || expiringSoon) && <AlertTriangle size={13} />}{expired ? `Expired ${Math.abs(days)}d ago` : expiringSoon ? `Expires in ${days}d` : `Valid until ${d.expiry_date}`}</p>}
      <div className="border-t border-navy-100 pt-3">{d.attachment ? <div className="flex items-center justify-between gap-2"><div className="min-w-0"><p className="text-xs font-medium text-emerald-700 flex items-center gap-1"><CheckCircle2 size={13} /> Attached</p><p className="text-xs text-navy-400 truncate" title={d.attachment.original_filename}>{d.attachment.original_filename}</p></div><button className="btn-outline !py-1.5 text-xs shrink-0" onClick={() => download(d)}><Download size={13} /> Download</button></div> : <div className="flex items-center justify-between gap-2"><p className="text-xs font-medium text-amber-dark">Not Uploaded</p><label className={`btn-amber !py-1.5 text-xs cursor-pointer shrink-0 ${uploadingId === d.id ? "opacity-60 pointer-events-none" : ""}`}><Upload size={13} /> {uploadingId === d.id ? "Uploading..." : "Upload"}<input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" className="hidden" onChange={(e) => uploadFor(d, e.target.files?.[0])} /></label></div>}</div>
    </div>; })}</div>}

    <Modal open={modalOpen} onClose={() => setModalOpen(false)} title="Add Document"><form onSubmit={handleSubmit} className="space-y-4"><div><label className="label">Belongs to</label><div className="flex gap-2"><button type="button" onClick={() => setForm({ ...form, target: "vehicle", driver_id: "" })} className={`btn flex-1 !py-2 text-xs ${form.target === "vehicle" ? "bg-navy-800 text-white" : "btn-outline"}`}>Vehicle</button><button type="button" onClick={() => setForm({ ...form, target: "driver", vehicle_id: "" })} className={`btn flex-1 !py-2 text-xs ${form.target === "driver" ? "bg-navy-800 text-white" : "btn-outline"}`}>Driver</button></div></div>
      {form.target === "vehicle" ? <div><label className="label">Vehicle</label><select required className="input" value={form.vehicle_id} onChange={(e) => setForm({ ...form, vehicle_id: e.target.value })}><option value="">Select a vehicle</option>{vehicles.map((v) => <option key={v.id} value={v.id}>{v.name} — {v.registration_number}</option>)}</select></div> : <div><label className="label">Driver</label><select required className="input" value={form.driver_id} onChange={(e) => setForm({ ...form, driver_id: e.target.value })}><option value="">Select a driver</option>{drivers.map((d) => <option key={d.id} value={d.id}>{d.full_name}</option>)}</select></div>}
      <div><label className="label">Document Type</label><select className="input" value={form.doc_type} onChange={(e) => setForm({ ...form, doc_type: e.target.value })}><option value="registration">Registration</option><option value="insurance">Insurance</option><option value="puc">PUC (Pollution Certificate)</option><option value="license">Driving License</option><option value="other">Other</option></select></div><div><label className="label">Document Number</label><input className="input" placeholder="Optional" value={form.doc_number} onChange={(e) => setForm({ ...form, doc_number: e.target.value })} /></div><div className="grid grid-cols-2 gap-4"><div><label className="label">Issue Date</label><input type="date" className="input" value={form.issue_date} onChange={(e) => setForm({ ...form, issue_date: e.target.value })} /></div><div><label className="label">Expiry Date</label><input type="date" className="input" value={form.expiry_date} onChange={(e) => setForm({ ...form, expiry_date: e.target.value })} /></div></div><div><label className="label">Attachment</label><label className="btn-outline w-full cursor-pointer justify-center"><Upload size={15} /> {form.file ? form.file.name : "Choose PDF / image"}<input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" className="hidden" onChange={(e) => setForm({ ...form, file: e.target.files?.[0] || null })} /></label></div><div><label className="label">Notes / Document Name</label><input className="input" placeholder="e.g. Fitness Certificate" value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></div><div className="flex justify-end gap-3 pt-2"><button type="button" className="btn-outline" onClick={() => setModalOpen(false)}>Cancel</button><button type="submit" disabled={saving} className="btn-amber">{saving ? "Saving..." : "Add Document"}</button></div></form></Modal>
    <ConfirmDialog open={!!deleteTarget} onClose={() => setDeleteTarget(null)} onConfirm={handleDelete} title="Delete document?" message="This will permanently remove the document record and its attached file." />
  </div>;
}
